### ISSUE TITLE
Change 'make test' to 'make template_example' in on_pr_master.yml workflow file

### ISSUE THREAD

**Issue by Neha-Sinha2305** [fredrikhgrelland/vagrant-hashistack-template#12]
https://github.com/fredrikhgrelland/vagrant-hashistack-template/pull/7

https://github.com/fredrikhgrelland/vagrant-hashistack-template/blob/c4dca7e92e055fb8b5843e10e470c6d1f8576596/.github/workflows/on_pr_push_master.yml#L112-L113

The above command does not trigger the code under 'template_example' and as such no tests are run so need to change it to ```make template_example```

**Comment by zhenik** [comment]
## Option 0
Change target in  `./.github/workflows/on_pr_push_master.yml`
```yml
 - name: Run make test 
   run: make template_example 
```

Downsides:
- Update documentation for [Getting started guide #272](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/272). 
Once the user creates a new module with using a template -> user need to change the next things:
- `./.github/workflows/on_pr_push_master.yml` -> `run: make test_example` to `run: make test`
- `./.github/workflows/on_pr_push_master.yml` -> `FILE_NAME: template_example/.env_override ` to `FILE_NAME: .env_override `

## Option 1 
Use the same target `test` in Makefile.

### Todo
- `test: clean up` to `test: clean template_example`
- `./.github/workflows/on_pr_push_master.yml` -> `FILE_NAME: .env_override ` to `FILE_NAME: template_example/.env_override `

Downsides: 
- Update documentation for [Getting started guide #272](https://github.com/fredrikhgrelland/vagrant-hashistack/issues/272). 
Once the user creates a new module with using a template -> user need to change the next things:
- `./Makefile` -> `test: clean template_example` to `test: clean up`
- `./.github/workflows/on_pr_push_master.yml` -> `FILE_NAME: template_example/.env_override ` to `FILE_NAME: .env_override `

## Option 2
Use two different targets in Makefile `test` and `test_example`, test both of them.

### Todo
- add changes to `./.github/workflows/on_pr_push_master.yml`

```yml
      - name: Make .env_override in order to matrix test template_example
        run: python .github/action/create-env.py
        env:
          ...
          FILE_NAME: template_example/.env_override
      
     - name: Make .env_override in order to matrix test root example
        run: python .github/action/create-env.py
        env:
          ...
          FILE_NAME: template_example/.env_override

      - name: Run make test
        run: make test

      - name: Run make test_example
        run: make template_example
```

Downsides:
- make cd/ci slower running example_template for the full test matrix

## Option 3
Igrone template_example test. Leave all as it is. close issue. close pr #15 without merging

## Option 4 #15
Modify the code in the **on_pr_master.yml** file so that it runs target **template_example** when triggered in [vagrant-hashistack-template](https://github.com/fredrikhgrelland/vagrant-hashistack-template ) repo and when run from other repos it would run the target **test**

**Example github action run** : [github action run](https://github.com/Neha-Sinha2305/terraform-nomad-presto/runs/1123384580?check_suite_focus=true)

**Example workflow file: **[workflow file]( https://github.com/Neha-Sinha2305/terraform-nomad-presto/actions/runs/257596550/workflow 
)
```yml
      - if: github.repository == 'fredrikhgrelland/vagrant-hashistack-template'
        name: Make .env_override in template_example dir in order to matrix test
        run: python .github/action/create-env.py
        env:
          ENVKEY_env_override: true
          ENVKEY_consul_acl: ${{ steps.consul_acl.outputs.consul_acl }}
          ENVKEY_consul_acl_default_policy: ${{ steps.consul_acl_default_policy.outputs.default_policy }}
          ENVKEY_nomad_acl: ${{ steps.nomad_acl.outputs.nomad_acl }}
          ENVKEY_consul_enterprise: ${{ steps.hashicorp_binary.outputs.consul_enterprise }}
          ENVKEY_nomad_enterprise: ${{ steps.hashicorp_binary.outputs.nomad_enterprise }}
          ENVKEY_vault_enterprise: ${{ steps.hashicorp_binary.outputs.vault_enterprise }}
          FILE_NAME: template_example/.env_override

      - if: github.repository == 'fredrikhgrelland/vagrant-hashistack-template'
        name: Run make template_example
        run: make template_example

      - if: github.repository != 'fredrikhgrelland/vagrant-hashistack-template'
        name: Make .env_override in template dir in order to matrix test
        run: python .github/action/create-env.py
        env:
          ENVKEY_env_override: true
          ENVKEY_consul_acl: ${{ steps.consul_acl.outputs.consul_acl }}
          ENVKEY_consul_acl_default_policy: ${{ steps.consul_acl_default_policy.outputs.default_policy }}
          ENVKEY_nomad_acl: ${{ steps.nomad_acl.outputs.nomad_acl }}
          ENVKEY_consul_enterprise: ${{ steps.hashicorp_binary.outputs.consul_enterprise }}
          ENVKEY_nomad_enterprise: ${{ steps.hashicorp_binary.outputs.nomad_enterprise }}
          ENVKEY_vault_enterprise: ${{ steps.hashicorp_binary.outputs.vault_enterprise }}
          FILE_NAME: .env_override

      - if: github.repository != 'fredrikhgrelland/vagrant-hashistack-template'
        name: Run make test
        run: make test
```
**Downsides:**
- little extra code in **on_pr_master.yml**
**Upsides:**
- Users of the template need not have to modify anything
